In [7]:
import numpy as np
a=np.array([0,1,2,3])
a
print(a)
a=np.arange()
print(a)

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [2]:

l=range(10000)

    
%timeit [i**2 for i in l]


5.88 ms ± 54.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
a=np.arange(10000)
%timeit a**2

13.4 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
a.ndim

1

In [7]:
a.shape


(10000,)

In [8]:
len(a)

10000

In [12]:
b = np.array([[0,1,2],[3,4,5]])
b


array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim


2

In [11]:
b.shape

(2, 3)

In [13]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
c.ndim


3

In [15]:
c.shape

(2, 2, 2)

In [17]:
#functions to create arrays

a=np.arange(10)
a
#print(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [22]:
a = np.linspace(0,1,6)     #0-1 is th size of arrau nd 6 is th data pts.
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
c=np.eye(3)   #it basically print the array with diagonal with value 1
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
c=np.eye(3,2)   
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [27]:
d = np.diag([1,2,3])    #automatically we get the matrics of {1-2-3}
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
np.diag(d)

array([1, 2, 3])

In [29]:
a = np.random.rand(4)
a

array([0.24965166, 0.73229908, 0.85157814, 0.42568576])

In [31]:
a = np.arange(64)
a
a.dtype

dtype('int32')

In [32]:
a = np.arange(10,dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
a = np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [35]:
d = np.array([1+2j,3+4j])
print(d.dtype)

complex128


In [38]:
d = np.array(["shubh","catalyst","machine","edutech"])
print(d.dtype)

<U8


In [39]:
a=np.arange(9)
print(a[5])


5


In [41]:
a = np.diag([1,2,3])
a[2,2]=20
a

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, 20]])

In [42]:
a= np.array([1,2,3,4,5])     #it will print the element from 2-4
a[2:4]

array([3, 4])

In [46]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
b = np.array(a)
b
b=a[::2]
b
b(0)

TypeError: 'numpy.ndarray' object is not callable

In [53]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [54]:
b[0]=50
b

array([50,  2,  4,  6,  8])

In [55]:
a

array([50,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [56]:
np.shares_memory(a,b)    #the operations which r performed on b will also reflect on a

True

In [58]:
c=a[::2].copy()
c

array([50,  2,  4,  6,  8])

In [59]:
np.shares_memory(a,c)

False

In [12]:
a = np.array([1,2,3,4])
b=a+1
b

array([2, 3, 4, 5])

In [13]:
a = np.array([1,2,3,4])
b=a*a
b

array([ 1,  4,  9, 16])

In [14]:
b = np.ones(4)+1

In [15]:
a-b

array([-1.,  0.,  1.,  2.])

In [19]:
c = np.diag([1,2,3,4])
print(c*c)
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [23]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [22]:
a<b


array([False, False, False, False])

In [24]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])

In [25]:
np.array_equal(a,c)

True

In [27]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,0,1],dtype=bool)
np.logical_or(a,b)

array([ True,  True, False,  True])

In [28]:
np.logical_and(a,b)

array([ True, False, False, False])

In [29]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [30]:
np.log(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [32]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [35]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [36]:
x.sum(axis=0)     #it will sum 2+1=3

array([3, 3])

In [42]:
x.sum(axis=1)     #it will sum 1+1=2 nd 2+2=4


array([2, 4])

In [43]:
x.argmin()    #index of the minimum


0

In [44]:
x.min()

1

In [46]:
x.argmax()

2

In [47]:
#logical operations
np.all([True, True,True])

True

In [48]:
np.any([True,False,False])


True

In [49]:
a=np.zeros((4,4))
np.any(a!=0)

False

In [50]:
np.all(a==a)

True

In [57]:
x = np.array([[1,2,3,1]])
y = np.array([[1,2,3],[5,6,2]])
x.mean()


1.75

In [58]:
np.median(x)

1.5

In [59]:
x.std()

0.82915619758885

In [63]:
import pandas
data = pandas.loadtxt("HEROMOTOCO.BO")
data

AttributeError: module 'pandas' has no attribute 'loadtxt'

In [69]:
import pandas as pd
data = pd.read_csv("TCS.NS.CSV")
print(data)

          Date         Open         High          Low        Close  \
0   2018-07-30  1943.000000  1954.699951  1931.550049  1944.599976   
1   2018-07-31  1942.000000  1947.000000  1928.000000  1940.199951   
2   2018-08-01  1949.949951  1981.550049  1949.800049  1976.500000   
3   2018-08-02  1980.000000  1985.000000  1945.000000  1948.400024   
4   2018-08-03  1956.500000  1982.050049  1956.500000  1979.449951   
5   2018-08-06  1997.000000  1998.949951  1972.250000  1975.550049   
6   2018-08-07  1978.199951  1979.150024  1960.500000  1967.349976   
7   2018-08-08  1972.000000  1978.300049  1962.000000  1974.000000   
8   2018-08-09  1980.000000  1980.800049  1966.000000  1974.349976   
9   2018-08-10  1980.949951  1996.500000  1972.050049  1993.099976   
10  2018-08-13  1997.800049  2004.250000  1990.000000  2000.150024   
11  2018-08-14  1992.000000  2024.599976  1982.400024  2003.550049   
12  2018-08-16  2000.300049  2020.050049  1995.000000  2008.500000   
13  2018-08-17  2013