In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [75]:
df = pd.read_csv("example_train1.csv")                     #read the data...

In [76]:
df

Document      Class
0          Catalyst  is a web educational institute.  education
1  Educational is also being good human and not j...  education
2  A story of great ethics and educational greatness  education
3                        Bahubali is king of cinemas     cinema
4                 good movie depends on good content     cinema

In [77]:
df["Class"]=df.Class.map({"education":1,"cinema":0})     #this function  is used to convert the education and cinema to 1 & 0...

In [78]:
df["Class"]

0    1
1    1
2    1
3    0
4    0
Name: Class, dtype: int64

In [79]:
from sklearn.feature_extraction.text import CountVectorizer
numpy_array=df.as_matrix()                              #make the matrix of the given data...
x=numpy_array[:,0]
y=numpy_array[:,1]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [80]:
y

array([1, 1, 1, 0, 0], dtype=object)

In [81]:
 vectorizer = CountVectorizer()
a = vectorizer.fit(x)                #in x variable we store our training data....
a

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [82]:
vectorizer.vocabulary_                          #it will assign the no. to every word in the sentence...

{'catalyst': 4,
 'is': 16,
 'web': 24,
 'educational': 9,
 'institute': 15,
 'also': 0,
 'being': 3,
 'good': 11,
 'human': 14,
 'and': 1,
 'not': 20,
 'just': 17,
 'degree': 7,
 'story': 23,
 'of': 21,
 'great': 12,
 'ethics': 10,
 'greatness': 13,
 'bahubali': 2,
 'king': 18,
 'cinemas': 5,
 'movie': 19,
 'depends': 8,
 'on': 22,
 'content': 6}

In [83]:
vector = CountVectorizer(stop_words='english')       #stop words mathod()
vector.fit(x)         #fit the training data....
vector.vocabulary_

{'catalyst': 1,
 'web': 17,
 'educational': 6,
 'institute': 12,
 'good': 8,
 'human': 11,
 'just': 13,
 'degree': 4,
 'story': 16,
 'great': 9,
 'ethics': 7,
 'greatness': 10,
 'bahubali': 0,
 'king': 14,
 'cinemas': 2,
 'movie': 15,
 'depends': 5,
 'content': 3}

In [84]:
print(vector.get_feature_names())

['bahubali', 'catalyst', 'cinemas', 'content', 'degree', 'depends', 'educational', 'ethics', 'good', 'great', 'greatness', 'human', 'institute', 'just', 'king', 'movie', 'story', 'web']


In [85]:
bow_matrix = vector.transform(x)

In [86]:
print(bow_matrix)

  (0, 1)	1
  (0, 6)	1
  (0, 12)	1
  (0, 17)	1
  (1, 4)	1
  (1, 6)	1
  (1, 8)	1
  (1, 11)	1
  (1, 13)	1
  (2, 6)	1
  (2, 7)	1
  (2, 9)	1
  (2, 10)	1
  (2, 16)	1
  (3, 0)	1
  (3, 2)	1
  (3, 14)	1
  (4, 3)	1
  (4, 5)	1
  (4, 8)	2
  (4, 15)	1


In [87]:
bow_matrix=bow_matrix.toarray()

In [88]:
print(bow_matrix)

[[0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 1 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 0 2 0 0 0 0 0 0 1 0 0]]


In [89]:
pd.DataFrame(bow_matrix,columns=vector.get_feature_names())

bahubali  catalyst  cinemas  content  degree  depends  educational  ethics  \
0         0         1        0        0       0        0            1       0   
1         0         0        0        0       1        0            1       0   
2         0         0        0        0       0        0            1       1   
3         1         0        1        0       0        0            0       0   
4         0         0        0        1       0        1            0       0   

   good  great  greatness  human  institute  just  king  movie  story  web  
0     0      0          0      0          1     0     0      0      0    1  
1     1      0          0      1          0     1     0      0      0    0  
2     0      1          1      0          0     0     0      0      1    0  
3     0      0          0      0          0     0     1      0      0    0  
4     2      0          0      0          0     0     0      1      0    0

In [90]:
df11 = pd.read_csv("test.csv") 

In [91]:
df11

Document  Class
0  very good educational institute.      1

In [92]:
from sklearn.feature_extraction.text import CountVectorizer
test_numpy_array=df11.as_matrix()                              #make the matrix of the given data...
x_test=test_numpy_array[:,0]

y_test=test_numpy_array[:,1]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [93]:
print(x_test)
print(y_test)

['very good educational institute.']
[1]


In [94]:
x_test_vector = vector.transform(x_test)
print(x_test_vector)       

  (0, 6)	1
  (0, 8)	1
  (0, 12)	1


In [95]:
x_test_vector.toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]],
      dtype=int64)

In [96]:
from sklearn.naive_bayes import MultinomialNB

In [97]:
nb = MultinomialNB()

In [98]:
x=bow_matrix
x

array([[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0]],
      dtype=int64)

In [100]:
y = y.astype('int')

In [101]:
y

array([1, 1, 1, 0, 0])

In [102]:
nb.fit(x,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [109]:
nb.predict_proba(x_test_vector)

array([[0.18899963, 0.81100037]])

In [110]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()

In [111]:
bnb.fit(x,y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [113]:
bnb.predict_proba(x_test_vector)

array([[0.06740789, 0.93259211]])